### ISSUE TITLE
Change request: Status Page domain name

### ISSUE THREAD

**Issue by victorskl** [umccr/data-portal-status-page#105]
Status Page domain name should change accordingly.
Also. When appropriate, happy for Status Page to use its own subdomain instead on Portal subdomain.
e.g.
```
https://status[.dev|.stg|.prod].umccr.org
```

**Comment by victorskl** [comment]
ditto:

https://github.com/umccr/data-portal-status-page/blob/87b8d0b5e908e33c334a19c966a475c080a18473/README.md?plain=1#L8-L9

**Comment by victorskl** [comment]
Related #104

**Comment by victorskl** [comment]
Ray pls see if you could tackle this story after #103

**Comment by raylrui** [comment]
sure @victorskl I will have a check of this.  Thanks

**Comment by raylrui** [comment]
So far:
For dev env, new url [https://status.dev.umccr.org](https://status.dev.umccr.org) has been applied.
For prod env,  we hold for now and we will apply new url when we push new update to prod

**Comment by raylrui** [comment]
We still need add our domain in allow origin, cognito call back and auth urls

[PR #689](https://github.com/umccr/data-portal-apis/pull/689) for adding domains in `allowedOrigins`
[PR #433](https://github.com/umccr/infrastructure/pull/433) for add status page `callback and redirect url` in dev env. So far we just hold new domain for prod for now

**Comment by victorskl** [comment]
Sure, I will review them now.

**Comment by raylrui** [comment]
Not sure if these are all we needed to migrate to new status page domain. need to check again if there are still something we need change.

I see your previous issue about new portal domain, just for reference https://github.com/umccr/infrastructure/issues/272

**Comment by victorskl** [comment]
Looks like new Status Page domain name https://status.dev.umccr.org work well now. 
Perhaps, we can close this ticket now, Ray?

**Comment by raylrui** [comment]
I am thinking if we need wait for new domain apply to stg, prod env. But all good for me to close this one.

**Comment by victorskl** [comment]
Good idea. Let us put this into review swim lane; park & wait.

**Comment by victorskl** [comment]
Sure, noted well about action items. I will perform those points when deploy to prod. And I will seek out your help if I stuck.

**Comment by victorskl** [comment]
Nice work, Ray. 

Your (refactored) Status Page is now live with new domain.!

https://status.umccr.org


Closing.
