### ISSUE TITLE
Status Page code refactor from javascript to typescript

### ISSUE THREAD

**Issue by raylrui** [umccr/data-portal-status-page#109]
For consistency reason, Status Page code need to refactor from javascript to typescript

1. add typescript support
2. add basic type support for all params and variable
3. refactor code structure

Related #93  and all other security issue from `npm audit`
Optional: use `yarn` and `vite` instead of `npm` and `webpack` to build for FE overall consistency

**Comment by victorskl** [comment]
+1 for vite and yarn
