### ISSUE TITLE
Aggregate BCL_CONVERT statuses into sequence run row

### ISSUE THREAD

**Issue by reisingerf** [umccr/data-portal-status-page#19]
As we are running the BCL_CONVERT workflow for **all** samples of any sequence run at the same time, there is little/no benefit in showing a per library status. 
It would be more intuitive/useful for users to see the conversion/demultiplexing status at the sequence run level.

Proposal:
- take out the BCL_CONVERT column in the per library table
- add a second status flag on each sequence run row that shows the BCL CONVERT workflow status for that run
- use the colour only to indicate status and use the label to define the type (for example: `conversion` and `sequencing`).

**Comment by williamputraintan** [comment]
Fix at commit c2d86f652683892eddda51b9b1bf7b8c1bf6bc3d
