### ISSUE TITLE
BCL Convert status label incorrect

### ISSUE THREAD

**Issue by reisingerf** [umccr/data-portal-status-page#30]
I noticed that the "BCL Convert" label in the status page is green (succeeded) for runs that are still ongoing.

Looking at the code [here](https://github.com/umccr/data-portal-status-page/blob/f0e31ee94229aba4e10d39afeca679c61a847cf6/src/components/sequenceRun/SequenceRunRow.js#L227) I was wondering if that should not take the workflow status into account rather than just if it is a BCL convert workflow (`isBclConvert`)?

**Comment by williamputraintan** [comment]
Currently it only check if bcl_convert workflow in the database without checking if status Succeed. Assuming that if the bcl_workflow exist at the database, the bcl_convert is done.

Fixing it now, following the end_status of the bcl_convert workflow.
