### ISSUE TITLE
No `info` field for failed worklows

### ISSUE THREAD

**Issue by ohofmann** [umccr/data-portal-status-page#52]
Clicking on the `i` icon (information) for failed workflow in https://status.data.umccr.org/workflows results in a blank page from which one cannot navigate back.

**Comment by reisingerf** [comment]
Confirmed. 
<img width="794" alt="Screen Shot 2022-05-19 at 9 37 27 am" src="https://user-images.githubusercontent.com/31906163/169172357-50dc46d3-3d3f-4e29-a150-629f6617eca3.png">

**Comment by reisingerf** [comment]
@williamputraintan addressing the `null` issue is one part and that fixes the TypeError.
However, why are there no records for a failed workflow in the first place? The data should be available whether the workflow failed or succeeded, no?
