### ISSUE TITLE
Potential row duplication in sequence page

### ISSUE THREAD

**Issue by ohofmann** [umccr/data-portal-status-page#53]
I am seeing some duplicated rows for tumor samples in the sequence page, e.g., for Instrument Run Id: 220513_A01052_0098_AHK5T2DSX3:

![image](https://user-images.githubusercontent.com/871172/169171470-0ec78880-6489-4c01-a341-bfeead417f4a.png)

This seems to be independent of the success or fail status but does not seem to apply to all samples.

**Comment by reisingerf** [comment]
Rows here represent LibraryRun entities (equivalent to FASTQ pairs produced by BCL Convert). 
So this can happen when a library is split across several lanes (you can add the lane column to check)
![Uploading Screen Shot 2022-05-19 at 9.32.50 am.png…]()

**Comment by reisingerf** [comment]
How to best show how LibraryRuns are related or grouped for any workflow is an open issue/question though

**Comment by ohofmann** [comment]
Got it. It might make sense to add the lane information as a default then to make this clear.

**Comment by reisingerf** [comment]
Agreed.
Just noting: we left it as at the minimum for now (there are other columns that for example show why some libraries didn't get run through certain workflows, etc.) with a view to improve it in the future.
We also thought about keeping user preferences in cookies, etc as your selection of columns is currently always reset and when switching around it quickly get's cumbersome to reselect your preferences.... WIP...
