### ISSUE TITLE
Workflow Status Upgrade

### ISSUE THREAD

**Issue by raylrui** [umccr/data-portal-status-page#97]
1. add new workflow status for WTS WGS: 
   ONCOANALYSER_WGS:"oncoanalyser_wgs",
  SASH: "sash",
  ONCOANALYSER_WGTS_BOTH:"oncoanalyser_wgts_existing_both",
  DRAGEN_WTS_QC: "wts_alignment_qc",
  RNASUM: "rnasum",
  STAR_ALIGNMENT: "star_alignment",
  ONCOANALYSER_WTS:"oncoanalyser_wts",

2. review workflows in type: "ctTSO", "ctDNA" and "Metagenm" to see if any workflows is missing or outdated

**Comment by victorskl** [comment]
Can this be closed as linked #98 PR is merged..?

**Comment by raylrui** [comment]
So far, we just have WTS, WGS, ctTSO, ctDNA in our status page, do we still need more workflow added? It is fine for now.

<img width="471" alt="image" src="https://github.com/umccr/data-portal-status-page/assets/160200168/63f114f3-546d-4fff-8ff4-bd77e336bec0">

**Comment by victorskl** [comment]
Right. Yup, that list good to me. So, it is fine for now.

**Comment by raylrui** [comment]
Current workflow is good for now.
